{
  "stats": {
    "suites": 7,
    "tests": 25,
    "passes": 16,
    "pending": 0,
    "failures": 9,
    "start": "2019-02-04T22:20:50.232Z",
    "end": "2019-02-04T22:20:50.509Z",
    "duration": 277
  },
  "tests": [
    {
      "title": "has an text input field",
      "fullTitle": "RestaurantInput has an text input field",
      "duration": 8,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "has an initial state with text key set to empty string",
      "fullTitle": "RestaurantInput has an initial state with text key set to empty string",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "changes the state on a keydown",
      "fullTitle": "RestaurantInput changes the state on a keydown",
      "duration": 2,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "updates the state of the store after submitting the form",
      "fullTitle": "RestaurantInput updates the state of the store after submitting the form",
      "duration": 46,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "displays a list of restaurant components",
      "fullTitle": "Restaurants Component displays a list of restaurant components",
      "duration": 9,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "displays the appropriate text",
      "fullTitle": "Restaurant Component displays the appropriate text",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "renders an li",
      "fullTitle": "Restaurant Component renders an li",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "has an unique id property for each element",
      "fullTitle": "RestaurantInput Component with Redux has an unique id property for each element",
      "duration": 11,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "has the restaurant as a prop",
      "fullTitle": "Restaurant Component with Redux has the restaurant as a prop",
      "duration": 7,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "has a button that dispatches a DELETE_RESTAURANT action with the proper id when clicked",
      "fullTitle": "Restaurant Component with Redux has a button that dispatches a DELETE_RESTAURANT action with the proper id when clicked",
      "duration": 7,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "updates the state of the store to remove the component",
      "fullTitle": "Restaurant Component with Redux updates the state of the store to remove the component",
      "duration": 37,
      "currentRetry": 0,
      "err": {
        "stack": "TypeError: Cannot read property 'filter' of undefined\n    at Reviews.render (src/components/reviews/Reviews.js:7:50)\n    at finishClassComponent (node_modules/react-dom/cjs/react-dom.development.js:14534:31)\n    at updateClassComponent (node_modules/react-dom/cjs/react-dom.development.js:14489:24)\n    at beginWork (node_modules/react-dom/cjs/react-dom.development.js:15335:16)\n    at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:18150:12)\n    at workLoop (node_modules/react-dom/cjs/react-dom.development.js:18190:24)\n    at renderRoot (node_modules/react-dom/cjs/react-dom.development.js:18276:7)\n    at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:19165:7)\n    at performWork (node_modules/react-dom/cjs/react-dom.development.js:19077:7)\n    at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:19051:3)\n    at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:19264:7)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1174:14\n    at Object.simulateEvent (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:405:15)\n    at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:933:29)\n    at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1702:25)\n    at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:932:21)\n    at Context.<anonymous> (test/restaurants-test.js:153:18)",
        "message": "Cannot read property 'filter' of undefined"
      }
    },
    {
      "title": "displays the ReviewInput component as a child of each Restaurant Component",
      "fullTitle": "ReviewInput Component displays the ReviewInput component as a child of each Restaurant Component",
      "duration": 4,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "has a text input field",
      "fullTitle": "ReviewInput Component has a text input field",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "has an initial state with text key set to empty string",
      "fullTitle": "ReviewInput Component has an initial state with text key set to empty string",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "has changes the state on a keydown",
      "fullTitle": "ReviewInput Component has changes the state on a keydown",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "adds a review to the store when the form is submitted",
      "fullTitle": "ReviewInput Component adds a review to the store when the form is submitted",
      "duration": 15,
      "currentRetry": 0,
      "err": {
        "stack": "Error: An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue.\n    at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:208:19)\n    at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:256:31)\n    at invokeGuardedCallbackAndCatchFirstError (node_modules/react-dom/cjs/react-dom.development.js:270:25)\n    at executeDispatch (node_modules/react-dom/cjs/react-dom.development.js:561:3)\n    at executeDispatchesInOrder (node_modules/react-dom/cjs/react-dom.development.js:583:5)\n    at executeDispatchesAndRelease (node_modules/react-dom/cjs/react-dom.development.js:680:5)\n    at executeDispatchesAndReleaseTopLevel (node_modules/react-dom/cjs/react-dom.development.js:688:10)\n    at forEachAccumulated (node_modules/react-dom/cjs/react-dom.development.js:662:8)\n    at runEventsInBatch (node_modules/react-dom/cjs/react-dom.development.js:816:3)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1178:7\n    at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:19260:12)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1174:14\n    at Object.simulateEvent (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:405:15)\n    at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:933:29)\n    at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1702:25)\n    at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:932:21)\n    at Context.<anonymous> (test/reviews-test.js:56:10)",
        "message": "An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue."
      }
    },
    {
      "title": "updates the state of the store after submitting the form",
      "fullTitle": "ReviewInput Component updates the state of the store after submitting the form",
      "duration": 7,
      "currentRetry": 0,
      "err": {
        "stack": "Error: An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue.\n    at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:208:19)\n    at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:256:31)\n    at invokeGuardedCallbackAndCatchFirstError (node_modules/react-dom/cjs/react-dom.development.js:270:25)\n    at executeDispatch (node_modules/react-dom/cjs/react-dom.development.js:561:3)\n    at executeDispatchesInOrder (node_modules/react-dom/cjs/react-dom.development.js:583:5)\n    at executeDispatchesAndRelease (node_modules/react-dom/cjs/react-dom.development.js:680:5)\n    at executeDispatchesAndReleaseTopLevel (node_modules/react-dom/cjs/react-dom.development.js:688:10)\n    at forEachAccumulated (node_modules/react-dom/cjs/react-dom.development.js:662:8)\n    at runEventsInBatch (node_modules/react-dom/cjs/react-dom.development.js:816:3)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1178:7\n    at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:19260:12)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1174:14\n    at Object.simulateEvent (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:405:15)\n    at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:933:29)\n    at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1702:25)\n    at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:932:21)\n    at Context.<anonymous> (test/reviews-test.js:73:10)",
        "message": "An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue."
      }
    },
    {
      "title": "sets a property of restaurantId on the review component from the parent components id",
      "fullTitle": "ReviewInput Component sets a property of restaurantId on the review component from the parent components id",
      "duration": 4,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "associates the review with the restaurant with a foreign key on the review",
      "fullTitle": "ReviewInput Component associates the review with the restaurant with a foreign key on the review",
      "duration": 7,
      "currentRetry": 0,
      "err": {
        "stack": "Error: An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue.\n    at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:208:19)\n    at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:256:31)\n    at invokeGuardedCallbackAndCatchFirstError (node_modules/react-dom/cjs/react-dom.development.js:270:25)\n    at executeDispatch (node_modules/react-dom/cjs/react-dom.development.js:561:3)\n    at executeDispatchesInOrder (node_modules/react-dom/cjs/react-dom.development.js:583:5)\n    at executeDispatchesAndRelease (node_modules/react-dom/cjs/react-dom.development.js:680:5)\n    at executeDispatchesAndReleaseTopLevel (node_modules/react-dom/cjs/react-dom.development.js:688:10)\n    at forEachAccumulated (node_modules/react-dom/cjs/react-dom.development.js:662:8)\n    at runEventsInBatch (node_modules/react-dom/cjs/react-dom.development.js:816:3)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1178:7\n    at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:19260:12)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1174:14\n    at Object.simulateEvent (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:405:15)\n    at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:933:29)\n    at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1702:25)\n    at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:932:21)\n    at Context.<anonymous> (test/reviews-test.js:99:16)",
        "message": "An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue."
      }
    },
    {
      "title": "is a child of the ReviewsContainer component",
      "fullTitle": "Reviews Component is a child of the ReviewsContainer component",
      "duration": 6,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "displays a review for when it is associated with the restaurant",
      "fullTitle": "Reviews Component displays a review for when it is associated with the restaurant",
      "duration": 5,
      "currentRetry": 0,
      "err": {
        "stack": "ReferenceError: restaurantId is not defined\n    at /home/Hector-Ariceaga/crud-lab-v-000/src/components/reviews/Reviews.js:7:91\n    at Array.filter (<anonymous>)\n    at Reviews.render (src/components/reviews/Reviews.js:7:50)\n    at finishClassComponent (node_modules/react-dom/cjs/react-dom.development.js:14534:31)\n    at updateClassComponent (node_modules/react-dom/cjs/react-dom.development.js:14489:24)\n    at beginWork (node_modules/react-dom/cjs/react-dom.development.js:15335:16)\n    at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:18150:12)\n    at workLoop (node_modules/react-dom/cjs/react-dom.development.js:18190:24)\n    at renderRoot (node_modules/react-dom/cjs/react-dom.development.js:18276:7)\n    at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:19165:7)\n    at performWork (node_modules/react-dom/cjs/react-dom.development.js:19077:7)\n    at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:19051:3)\n    at requestWork (node_modules/react-dom/cjs/react-dom.development.js:18920:5)\n    at scheduleWork (node_modules/react-dom/cjs/react-dom.development.js:18729:5)\n    at scheduleRootUpdate (node_modules/react-dom/cjs/react-dom.development.js:19397:3)\n    at updateContainerAtExpirationTime (node_modules/react-dom/cjs/react-dom.development.js:19425:10)\n    at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:19482:10)\n    at ReactRoot.render (node_modules/react-dom/cjs/react-dom.development.js:19774:3)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom.development.js:19914:14\n    at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:19280:10)\n    at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:19910:5)\n    at Object.render (node_modules/react-dom/cjs/react-dom.development.js:19971:12)\n    at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:360:114)\n    at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:134:16)\n    at mount (node_modules/enzyme/build/mount.js:21:10)\n    at Context.<anonymous> (test/reviews-test.js:122:21)",
        "message": "restaurantId is not defined"
      }
    },
    {
      "title": "does not display any review unassociated with the restaurant",
      "fullTitle": "Reviews Component does not display any review unassociated with the restaurant",
      "duration": 4,
      "currentRetry": 0,
      "err": {
        "stack": "ReferenceError: restaurantId is not defined\n    at /home/Hector-Ariceaga/crud-lab-v-000/src/components/reviews/Reviews.js:7:91\n    at Array.filter (<anonymous>)\n    at Reviews.render (src/components/reviews/Reviews.js:7:50)\n    at finishClassComponent (node_modules/react-dom/cjs/react-dom.development.js:14534:31)\n    at updateClassComponent (node_modules/react-dom/cjs/react-dom.development.js:14489:24)\n    at beginWork (node_modules/react-dom/cjs/react-dom.development.js:15335:16)\n    at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:18150:12)\n    at workLoop (node_modules/react-dom/cjs/react-dom.development.js:18190:24)\n    at renderRoot (node_modules/react-dom/cjs/react-dom.development.js:18276:7)\n    at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:19165:7)\n    at performWork (node_modules/react-dom/cjs/react-dom.development.js:19077:7)\n    at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:19051:3)\n    at requestWork (node_modules/react-dom/cjs/react-dom.development.js:18920:5)\n    at scheduleWork (node_modules/react-dom/cjs/react-dom.development.js:18729:5)\n    at scheduleRootUpdate (node_modules/react-dom/cjs/react-dom.development.js:19397:3)\n    at updateContainerAtExpirationTime (node_modules/react-dom/cjs/react-dom.development.js:19425:10)\n    at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:19482:10)\n    at ReactRoot.render (node_modules/react-dom/cjs/react-dom.development.js:19774:3)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom.development.js:19914:14\n    at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:19280:10)\n    at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:19910:5)\n    at Object.render (node_modules/react-dom/cjs/react-dom.development.js:19971:12)\n    at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:360:114)\n    at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:134:16)\n    at mount (node_modules/enzyme/build/mount.js:21:10)\n    at Context.<anonymous> (test/reviews-test.js:135:21)",
        "message": "restaurantId is not defined"
      }
    },
    {
      "title": "has an unique id property that for each element",
      "fullTitle": "Reviews Component has an unique id property that for each element",
      "duration": 8,
      "currentRetry": 0,
      "err": {
        "stack": "Error: An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue.\n    at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:208:19)\n    at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:256:31)\n    at invokeGuardedCallbackAndCatchFirstError (node_modules/react-dom/cjs/react-dom.development.js:270:25)\n    at executeDispatch (node_modules/react-dom/cjs/react-dom.development.js:561:3)\n    at executeDispatchesInOrder (node_modules/react-dom/cjs/react-dom.development.js:583:5)\n    at executeDispatchesAndRelease (node_modules/react-dom/cjs/react-dom.development.js:680:5)\n    at executeDispatchesAndReleaseTopLevel (node_modules/react-dom/cjs/react-dom.development.js:688:10)\n    at forEachAccumulated (node_modules/react-dom/cjs/react-dom.development.js:662:8)\n    at runEventsInBatch (node_modules/react-dom/cjs/react-dom.development.js:816:3)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1178:7\n    at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:19260:12)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1174:14\n    at Object.simulateEvent (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:405:15)\n    at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:933:29)\n    at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1702:25)\n    at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:932:21)\n    at Context.<anonymous> (test/reviews-test.js:149:16)",
        "message": "An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue."
      }
    },
    {
      "title": "has a button that dispatches a DELETE_REVIEW action when clicked",
      "fullTitle": "Reviews Component has a button that dispatches a DELETE_REVIEW action when clicked",
      "duration": 4,
      "currentRetry": 0,
      "err": {
        "stack": "ReferenceError: restaurantId is not defined\n    at /home/Hector-Ariceaga/crud-lab-v-000/src/components/reviews/Reviews.js:7:91\n    at Array.filter (<anonymous>)\n    at Reviews.render (src/components/reviews/Reviews.js:7:50)\n    at finishClassComponent (node_modules/react-dom/cjs/react-dom.development.js:14534:31)\n    at updateClassComponent (node_modules/react-dom/cjs/react-dom.development.js:14489:24)\n    at beginWork (node_modules/react-dom/cjs/react-dom.development.js:15335:16)\n    at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:18150:12)\n    at workLoop (node_modules/react-dom/cjs/react-dom.development.js:18190:24)\n    at renderRoot (node_modules/react-dom/cjs/react-dom.development.js:18276:7)\n    at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:19165:7)\n    at performWork (node_modules/react-dom/cjs/react-dom.development.js:19077:7)\n    at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:19051:3)\n    at requestWork (node_modules/react-dom/cjs/react-dom.development.js:18920:5)\n    at scheduleWork (node_modules/react-dom/cjs/react-dom.development.js:18729:5)\n    at scheduleRootUpdate (node_modules/react-dom/cjs/react-dom.development.js:19397:3)\n    at updateContainerAtExpirationTime (node_modules/react-dom/cjs/react-dom.development.js:19425:10)\n    at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:19482:10)\n    at ReactRoot.render (node_modules/react-dom/cjs/react-dom.development.js:19774:3)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom.development.js:19914:14\n    at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:19280:10)\n    at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:19910:5)\n    at Object.render (node_modules/react-dom/cjs/react-dom.development.js:19971:12)\n    at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:360:114)\n    at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:134:16)\n    at mount (node_modules/enzyme/build/mount.js:21:10)\n    at Context.<anonymous> (test/reviews-test.js:165:21)",
        "message": "restaurantId is not defined"
      }
    },
    {
      "title": "updates the state of the store to remove the component",
      "fullTitle": "Reviews Component updates the state of the store to remove the component",
      "duration": 11,
      "currentRetry": 0,
      "err": {
        "stack": "Error: An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue.\n    at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:208:19)\n    at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:256:31)\n    at invokeGuardedCallbackAndCatchFirstError (node_modules/react-dom/cjs/react-dom.development.js:270:25)\n    at executeDispatch (node_modules/react-dom/cjs/react-dom.development.js:561:3)\n    at executeDispatchesInOrder (node_modules/react-dom/cjs/react-dom.development.js:583:5)\n    at executeDispatchesAndRelease (node_modules/react-dom/cjs/react-dom.development.js:680:5)\n    at executeDispatchesAndReleaseTopLevel (node_modules/react-dom/cjs/react-dom.development.js:688:10)\n    at forEachAccumulated (node_modules/react-dom/cjs/react-dom.development.js:662:8)\n    at runEventsInBatch (node_modules/react-dom/cjs/react-dom.development.js:816:3)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1178:7\n    at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:19260:12)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1174:14\n    at Object.simulateEvent (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:405:15)\n    at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:933:29)\n    at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1702:25)\n    at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:932:21)\n    at Context.<anonymous> (test/reviews-test.js:186:10)",
        "message": "An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue."
      }
    }
  ],
  "pending": [],
  "failures": [
    {
      "title": "updates the state of the store to remove the component",
      "fullTitle": "Restaurant Component with Redux updates the state of the store to remove the component",
      "duration": 37,
      "currentRetry": 0,
      "err": {
        "stack": "TypeError: Cannot read property 'filter' of undefined\n    at Reviews.render (src/components/reviews/Reviews.js:7:50)\n    at finishClassComponent (node_modules/react-dom/cjs/react-dom.development.js:14534:31)\n    at updateClassComponent (node_modules/react-dom/cjs/react-dom.development.js:14489:24)\n    at beginWork (node_modules/react-dom/cjs/react-dom.development.js:15335:16)\n    at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:18150:12)\n    at workLoop (node_modules/react-dom/cjs/react-dom.development.js:18190:24)\n    at renderRoot (node_modules/react-dom/cjs/react-dom.development.js:18276:7)\n    at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:19165:7)\n    at performWork (node_modules/react-dom/cjs/react-dom.development.js:19077:7)\n    at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:19051:3)\n    at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:19264:7)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1174:14\n    at Object.simulateEvent (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:405:15)\n    at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:933:29)\n    at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1702:25)\n    at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:932:21)\n    at Context.<anonymous> (test/restaurants-test.js:153:18)",
        "message": "Cannot read property 'filter' of undefined"
      }
    },
    {
      "title": "adds a review to the store when the form is submitted",
      "fullTitle": "ReviewInput Component adds a review to the store when the form is submitted",
      "duration": 15,
      "currentRetry": 0,
      "err": {
        "stack": "Error: An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue.\n    at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:208:19)\n    at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:256:31)\n    at invokeGuardedCallbackAndCatchFirstError (node_modules/react-dom/cjs/react-dom.development.js:270:25)\n    at executeDispatch (node_modules/react-dom/cjs/react-dom.development.js:561:3)\n    at executeDispatchesInOrder (node_modules/react-dom/cjs/react-dom.development.js:583:5)\n    at executeDispatchesAndRelease (node_modules/react-dom/cjs/react-dom.development.js:680:5)\n    at executeDispatchesAndReleaseTopLevel (node_modules/react-dom/cjs/react-dom.development.js:688:10)\n    at forEachAccumulated (node_modules/react-dom/cjs/react-dom.development.js:662:8)\n    at runEventsInBatch (node_modules/react-dom/cjs/react-dom.development.js:816:3)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1178:7\n    at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:19260:12)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1174:14\n    at Object.simulateEvent (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:405:15)\n    at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:933:29)\n    at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1702:25)\n    at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:932:21)\n    at Context.<anonymous> (test/reviews-test.js:56:10)",
        "message": "An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue."
      }
    },
    {
      "title": "updates the state of the store after submitting the form",
      "fullTitle": "ReviewInput Component updates the state of the store after submitting the form",
      "duration": 7,
      "currentRetry": 0,
      "err": {
        "stack": "Error: An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue.\n    at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:208:19)\n    at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:256:31)\n    at invokeGuardedCallbackAndCatchFirstError (node_modules/react-dom/cjs/react-dom.development.js:270:25)\n    at executeDispatch (node_modules/react-dom/cjs/react-dom.development.js:561:3)\n    at executeDispatchesInOrder (node_modules/react-dom/cjs/react-dom.development.js:583:5)\n    at executeDispatchesAndRelease (node_modules/react-dom/cjs/react-dom.development.js:680:5)\n    at executeDispatchesAndReleaseTopLevel (node_modules/react-dom/cjs/react-dom.development.js:688:10)\n    at forEachAccumulated (node_modules/react-dom/cjs/react-dom.development.js:662:8)\n    at runEventsInBatch (node_modules/react-dom/cjs/react-dom.development.js:816:3)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1178:7\n    at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:19260:12)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1174:14\n    at Object.simulateEvent (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:405:15)\n    at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:933:29)\n    at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1702:25)\n    at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:932:21)\n    at Context.<anonymous> (test/reviews-test.js:73:10)",
        "message": "An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue."
      }
    },
    {
      "title": "associates the review with the restaurant with a foreign key on the review",
      "fullTitle": "ReviewInput Component associates the review with the restaurant with a foreign key on the review",
      "duration": 7,
      "currentRetry": 0,
      "err": {
        "stack": "Error: An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue.\n    at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:208:19)\n    at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:256:31)\n    at invokeGuardedCallbackAndCatchFirstError (node_modules/react-dom/cjs/react-dom.development.js:270:25)\n    at executeDispatch (node_modules/react-dom/cjs/react-dom.development.js:561:3)\n    at executeDispatchesInOrder (node_modules/react-dom/cjs/react-dom.development.js:583:5)\n    at executeDispatchesAndRelease (node_modules/react-dom/cjs/react-dom.development.js:680:5)\n    at executeDispatchesAndReleaseTopLevel (node_modules/react-dom/cjs/react-dom.development.js:688:10)\n    at forEachAccumulated (node_modules/react-dom/cjs/react-dom.development.js:662:8)\n    at runEventsInBatch (node_modules/react-dom/cjs/react-dom.development.js:816:3)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1178:7\n    at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:19260:12)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1174:14\n    at Object.simulateEvent (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:405:15)\n    at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:933:29)\n    at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1702:25)\n    at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:932:21)\n    at Context.<anonymous> (test/reviews-test.js:99:16)",
        "message": "An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue."
      }
    },
    {
      "title": "displays a review for when it is associated with the restaurant",
      "fullTitle": "Reviews Component displays a review for when it is associated with the restaurant",
      "duration": 5,
      "currentRetry": 0,
      "err": {
        "stack": "ReferenceError: restaurantId is not defined\n    at /home/Hector-Ariceaga/crud-lab-v-000/src/components/reviews/Reviews.js:7:91\n    at Array.filter (<anonymous>)\n    at Reviews.render (src/components/reviews/Reviews.js:7:50)\n    at finishClassComponent (node_modules/react-dom/cjs/react-dom.development.js:14534:31)\n    at updateClassComponent (node_modules/react-dom/cjs/react-dom.development.js:14489:24)\n    at beginWork (node_modules/react-dom/cjs/react-dom.development.js:15335:16)\n    at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:18150:12)\n    at workLoop (node_modules/react-dom/cjs/react-dom.development.js:18190:24)\n    at renderRoot (node_modules/react-dom/cjs/react-dom.development.js:18276:7)\n    at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:19165:7)\n    at performWork (node_modules/react-dom/cjs/react-dom.development.js:19077:7)\n    at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:19051:3)\n    at requestWork (node_modules/react-dom/cjs/react-dom.development.js:18920:5)\n    at scheduleWork (node_modules/react-dom/cjs/react-dom.development.js:18729:5)\n    at scheduleRootUpdate (node_modules/react-dom/cjs/react-dom.development.js:19397:3)\n    at updateContainerAtExpirationTime (node_modules/react-dom/cjs/react-dom.development.js:19425:10)\n    at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:19482:10)\n    at ReactRoot.render (node_modules/react-dom/cjs/react-dom.development.js:19774:3)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom.development.js:19914:14\n    at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:19280:10)\n    at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:19910:5)\n    at Object.render (node_modules/react-dom/cjs/react-dom.development.js:19971:12)\n    at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:360:114)\n    at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:134:16)\n    at mount (node_modules/enzyme/build/mount.js:21:10)\n    at Context.<anonymous> (test/reviews-test.js:122:21)",
        "message": "restaurantId is not defined"
      }
    },
    {
      "title": "does not display any review unassociated with the restaurant",
      "fullTitle": "Reviews Component does not display any review unassociated with the restaurant",
      "duration": 4,
      "currentRetry": 0,
      "err": {
        "stack": "ReferenceError: restaurantId is not defined\n    at /home/Hector-Ariceaga/crud-lab-v-000/src/components/reviews/Reviews.js:7:91\n    at Array.filter (<anonymous>)\n    at Reviews.render (src/components/reviews/Reviews.js:7:50)\n    at finishClassComponent (node_modules/react-dom/cjs/react-dom.development.js:14534:31)\n    at updateClassComponent (node_modules/react-dom/cjs/react-dom.development.js:14489:24)\n    at beginWork (node_modules/react-dom/cjs/react-dom.development.js:15335:16)\n    at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:18150:12)\n    at workLoop (node_modules/react-dom/cjs/react-dom.development.js:18190:24)\n    at renderRoot (node_modules/react-dom/cjs/react-dom.development.js:18276:7)\n    at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:19165:7)\n    at performWork (node_modules/react-dom/cjs/react-dom.development.js:19077:7)\n    at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:19051:3)\n    at requestWork (node_modules/react-dom/cjs/react-dom.development.js:18920:5)\n    at scheduleWork (node_modules/react-dom/cjs/react-dom.development.js:18729:5)\n    at scheduleRootUpdate (node_modules/react-dom/cjs/react-dom.development.js:19397:3)\n    at updateContainerAtExpirationTime (node_modules/react-dom/cjs/react-dom.development.js:19425:10)\n    at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:19482:10)\n    at ReactRoot.render (node_modules/react-dom/cjs/react-dom.development.js:19774:3)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom.development.js:19914:14\n    at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:19280:10)\n    at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:19910:5)\n    at Object.render (node_modules/react-dom/cjs/react-dom.development.js:19971:12)\n    at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:360:114)\n    at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:134:16)\n    at mount (node_modules/enzyme/build/mount.js:21:10)\n    at Context.<anonymous> (test/reviews-test.js:135:21)",
        "message": "restaurantId is not defined"
      }
    },
    {
      "title": "has an unique id property that for each element",
      "fullTitle": "Reviews Component has an unique id property that for each element",
      "duration": 8,
      "currentRetry": 0,
      "err": {
        "stack": "Error: An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue.\n    at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:208:19)\n    at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:256:31)\n    at invokeGuardedCallbackAndCatchFirstError (node_modules/react-dom/cjs/react-dom.development.js:270:25)\n    at executeDispatch (node_modules/react-dom/cjs/react-dom.development.js:561:3)\n    at executeDispatchesInOrder (node_modules/react-dom/cjs/react-dom.development.js:583:5)\n    at executeDispatchesAndRelease (node_modules/react-dom/cjs/react-dom.development.js:680:5)\n    at executeDispatchesAndReleaseTopLevel (node_modules/react-dom/cjs/react-dom.development.js:688:10)\n    at forEachAccumulated (node_modules/react-dom/cjs/react-dom.development.js:662:8)\n    at runEventsInBatch (node_modules/react-dom/cjs/react-dom.development.js:816:3)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1178:7\n    at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:19260:12)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1174:14\n    at Object.simulateEvent (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:405:15)\n    at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:933:29)\n    at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1702:25)\n    at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:932:21)\n    at Context.<anonymous> (test/reviews-test.js:149:16)",
        "message": "An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue."
      }
    },
    {
      "title": "has a button that dispatches a DELETE_REVIEW action when clicked",
      "fullTitle": "Reviews Component has a button that dispatches a DELETE_REVIEW action when clicked",
      "duration": 4,
      "currentRetry": 0,
      "err": {
        "stack": "ReferenceError: restaurantId is not defined\n    at /home/Hector-Ariceaga/crud-lab-v-000/src/components/reviews/Reviews.js:7:91\n    at Array.filter (<anonymous>)\n    at Reviews.render (src/components/reviews/Reviews.js:7:50)\n    at finishClassComponent (node_modules/react-dom/cjs/react-dom.development.js:14534:31)\n    at updateClassComponent (node_modules/react-dom/cjs/react-dom.development.js:14489:24)\n    at beginWork (node_modules/react-dom/cjs/react-dom.development.js:15335:16)\n    at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:18150:12)\n    at workLoop (node_modules/react-dom/cjs/react-dom.development.js:18190:24)\n    at renderRoot (node_modules/react-dom/cjs/react-dom.development.js:18276:7)\n    at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:19165:7)\n    at performWork (node_modules/react-dom/cjs/react-dom.development.js:19077:7)\n    at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:19051:3)\n    at requestWork (node_modules/react-dom/cjs/react-dom.development.js:18920:5)\n    at scheduleWork (node_modules/react-dom/cjs/react-dom.development.js:18729:5)\n    at scheduleRootUpdate (node_modules/react-dom/cjs/react-dom.development.js:19397:3)\n    at updateContainerAtExpirationTime (node_modules/react-dom/cjs/react-dom.development.js:19425:10)\n    at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:19482:10)\n    at ReactRoot.render (node_modules/react-dom/cjs/react-dom.development.js:19774:3)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom.development.js:19914:14\n    at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:19280:10)\n    at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:19910:5)\n    at Object.render (node_modules/react-dom/cjs/react-dom.development.js:19971:12)\n    at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:360:114)\n    at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:134:16)\n    at mount (node_modules/enzyme/build/mount.js:21:10)\n    at Context.<anonymous> (test/reviews-test.js:165:21)",
        "message": "restaurantId is not defined"
      }
    },
    {
      "title": "updates the state of the store to remove the component",
      "fullTitle": "Reviews Component updates the state of the store to remove the component",
      "duration": 11,
      "currentRetry": 0,
      "err": {
        "stack": "Error: An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue.\n    at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:208:19)\n    at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:256:31)\n    at invokeGuardedCallbackAndCatchFirstError (node_modules/react-dom/cjs/react-dom.development.js:270:25)\n    at executeDispatch (node_modules/react-dom/cjs/react-dom.development.js:561:3)\n    at executeDispatchesInOrder (node_modules/react-dom/cjs/react-dom.development.js:583:5)\n    at executeDispatchesAndRelease (node_modules/react-dom/cjs/react-dom.development.js:680:5)\n    at executeDispatchesAndReleaseTopLevel (node_modules/react-dom/cjs/react-dom.development.js:688:10)\n    at forEachAccumulated (node_modules/react-dom/cjs/react-dom.development.js:662:8)\n    at runEventsInBatch (node_modules/react-dom/cjs/react-dom.development.js:816:3)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1178:7\n    at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:19260:12)\n    at /home/Hector-Ariceaga/crud-lab-v-000/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1174:14\n    at Object.simulateEvent (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:405:15)\n    at ReactWrapper.<anonymous> (node_modules/enzyme/build/ReactWrapper.js:933:29)\n    at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1702:25)\n    at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:932:21)\n    at Context.<anonymous> (test/reviews-test.js:186:10)",
        "message": "An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the \"Pause on exceptions\" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue."
      }
    }
  ],
  "passes": [
    {
      "title": "has an text input field",
      "fullTitle": "RestaurantInput has an text input field",
      "duration": 8,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "has an initial state with text key set to empty string",
      "fullTitle": "RestaurantInput has an initial state with text key set to empty string",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "changes the state on a keydown",
      "fullTitle": "RestaurantInput changes the state on a keydown",
      "duration": 2,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "updates the state of the store after submitting the form",
      "fullTitle": "RestaurantInput updates the state of the store after submitting the form",
      "duration": 46,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "displays a list of restaurant components",
      "fullTitle": "Restaurants Component displays a list of restaurant components",
      "duration": 9,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "displays the appropriate text",
      "fullTitle": "Restaurant Component displays the appropriate text",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "renders an li",
      "fullTitle": "Restaurant Component renders an li",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "has an unique id property for each element",
      "fullTitle": "RestaurantInput Component with Redux has an unique id property for each element",
      "duration": 11,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "has the restaurant as a prop",
      "fullTitle": "Restaurant Component with Redux has the restaurant as a prop",
      "duration": 7,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "has a button that dispatches a DELETE_RESTAURANT action with the proper id when clicked",
      "fullTitle": "Restaurant Component with Redux has a button that dispatches a DELETE_RESTAURANT action with the proper id when clicked",
      "duration": 7,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "displays the ReviewInput component as a child of each Restaurant Component",
      "fullTitle": "ReviewInput Component displays the ReviewInput component as a child of each Restaurant Component",
      "duration": 4,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "has a text input field",
      "fullTitle": "ReviewInput Component has a text input field",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "has an initial state with text key set to empty string",
      "fullTitle": "ReviewInput Component has an initial state with text key set to empty string",
      "duration": 0,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "has changes the state on a keydown",
      "fullTitle": "ReviewInput Component has changes the state on a keydown",
      "duration": 1,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "sets a property of restaurantId on the review component from the parent components id",
      "fullTitle": "ReviewInput Component sets a property of restaurantId on the review component from the parent components id",
      "duration": 4,
      "currentRetry": 0,
      "err": {}
    },
    {
      "title": "is a child of the ReviewsContainer component",
      "fullTitle": "Reviews Component is a child of the ReviewsContainer component",
      "duration": 6,
      "currentRetry": 0,
      "err": {}
    }
  ]
}